# Generated by Django 5.2.5 on 2025-08-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appShop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Foto'),
        ),
    ]
